version: '3'

services:

  app:
    build: .
    volumes:
      -  .:/app
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eulabs
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
